### PR TITLE
Fix new id-pairs for DDBJ-related

### PR DESCRIPTION
**Pull request by aghelfi-ddbj**
Fixed config.yaml and removed version from assembly_genome.

### CODE REVIEW

**Comment by aghelfi-ddbj** [comment]
Added pair:  ncbi_biosample_bioproject (source file: biosample_set.xml.gz)

**Comment by aghelfi-ddbj** [comment]
Added pair taxonomy_id - biosample

**Comment by aghelfi-ddbj** [comment]
Added pair sequence accession - taxon ID

**Comment by aghelfi-ddbj** [comment]
Added pair gea - biosample

**Comment by aghelfi-ddbj** [comment]
Added pair gea - bioproject

**Comment by aghelfi-ddbj** [comment]
Added pair: 
bioproject_umbrella - bioproject

**Comment by aghelfi-ddbj** [comment]
Added pair: bioproject - biosample. From trad and trace databases.

**Comment by aghelfi-ddbj** [comment]
Added pair: biosample - bioproject. From trad and trace databases.

**Comment by aghelfi-ddbj** [comment]
Added pair: assembly_genome - insdc (wgs.master)

**Comment by sh-ikeda** [comment]
I closed this PR by mistake. My apologies.
It seems that I can not reopen this. Could you send the PR again? @aghelfi-ddbj

**Comment by sh-ikeda** [comment]
I'm sorry for bothering you. Sending the PR from your current fork may be difficult because I destroyed the commit history of the main repo.
Following these steps can be an easier way.

1. Delete your fork once.
2. Fork the main repo again.
3. Clone the fork to your local machine.
4. Commit your works again.
5. Send PR.

I apologize again for troubling you.

**Pull request closed without merging**
